# Code generated by PyGo transpiler. DO NOT EDIT.
from __future__ import annotations
from datetime import datetime
from decimal import Decimal

# Handlers register into the shared HANDLERS dict owned by the runtime client,
# so the pyclient serve loop can dispatch to them over the socket.
from core.runtime.pyclient import HANDLERS

class Greeting:
    """Generated ORM model from `model Greeting`."""

    id: str | None
    name: str

    def __init__(self, **kwargs):
        self.id = kwargs.get("id")
        self.name = kwargs.get("name")

    @classmethod
    def find(cls, id):
        """Look up a Greeting by id. TODO: wire to the datastore."""
        raise NotImplementedError("ORM find() not implemented in Fase 0")


def hello(name: str) -> Greeting:
    return Greeting(name=name)
HANDLERS["hello"] = hello

