// Code generated by PyGo transpiler. DO NOT EDIT.
package generated

import (
	"time"

	"github.com/ander-labs/pygo/core/runtime"
)

// ensure time is referenced even if no model uses DateTime.
var _ = time.Now

// Greeting is generated from the `model Greeting` declaration.
type Greeting struct {
	Id *string `json:"id" msgpack:"id"`
	Name string `json:"name" msgpack:"name"`
}

// Handler_hello delegates to the Python handler "hello" over the MessagePack socket.
func Handler_hello(args map[string]interface{}) (Greeting, error) {
	// Build the msgpack payload {handler, args}.
	payload := map[string]interface{}{
		"handler": "hello",
		"args":    args,
	}
	// TODO(runtime-agent): runtime.CallPython must serialize `payload` with
	// msgpack, write it to the UDS socket, read the response and decode it.
	// This helper is implemented by the runtime/socket agent.
	resp, err := runtime.CallPython("hello", payload)
	if err != nil {
		var zero Greeting
		return zero, err
	}
	// TODO(runtime-agent): decode resp into Greeting.
	_ = resp
	var out Greeting
	return out, nil
}

// RegisterRoutes wires the generated routes into a router.
// The router type is intentionally an interface stub for Fase 0; the
// supervisor/HTTP agent supplies the concrete router.
type Router interface {
	Handle(method, path string, h func(args map[string]interface{}) (interface{}, error))
}

func RegisterRoutes(r Router) {
	r.Handle("GET", "/hello/:name", func(args map[string]interface{}) (interface{}, error) {
		return Handler_hello(args)
	})
}
