package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// runBuild builds the project for production.
//
// `pygo build --embed-python` generates a PyOxidizer spec (pyoxidizer.bzl) that
// bundles CPython + the app's Python modules (gen_py.py, core.runtime.pyclient)
// into a single self-contained binary. If the `pyoxidizer` CLI is on PATH it is
// invoked; otherwise the spec is written and the user runs it on a machine with
// Rust/PyOxidizer (we avoid pulling that toolchain here).
func runBuild(args []string) error {
	fs := flag.NewFlagSet("build", flag.ContinueOnError)
	embedPython := fs.Bool("embed-python", false, "embed the Python interpreter into a single binary via PyOxidizer")
	out := fs.String("o", "dist/app", "output binary path")
	fs.Usage = func() {
		fmt.Fprintln(os.Stderr, "Usage: pygo build [flags]")
		fs.PrintDefaults()
	}
	if err := fs.Parse(args); err != nil {
		return err
	}

	pgo, err := findFirstPgo(".")
	if err != nil {
		return err
	}
	projectDir := filepath.Dir(pgo)

	if *embedPython {
		specPath := filepath.Join(projectDir, "pyoxidizer.bzl")
		if err := writePyoxidizerSpec(specPath, projectDir); err != nil {
			return err
		}
		fmt.Printf("build: wrote PyOxidizer spec -> %s\n", specPath)

		pyo, err := exec.LookPath("pyoxidizer")
		if err != nil {
			fmt.Println("build: `pyoxidizer` not on PATH — skipping the heavy build here.")
			fmt.Println("       Run on a machine with Rust + PyOxidizer installed:")
			fmt.Printf("         cd %s && pyoxidizer build --release\n", projectDir)
			fmt.Printf("       The resulting binary will serve without python3/venv.\n")
			return nil
		}
		cmd := exec.Command(pyo, "build", "--release")
		cmd.Dir = projectDir
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("pyoxidizer build failed: %w", err)
		}
		fmt.Printf("build: produced embedded binary at %s\n", *out)
		return nil
	}

	// Dev-style build: compile the Go supervisor only; Python runs from the
	// system interpreter / venv.
	fmt.Println("build: dev-style build (Python runs from system interpreter).")
	fmt.Println("       Use --embed-python for a single self-contained binary.")
	return nil
}

// writePyoxidizerSpec writes a minimal, dependency-light PyOxidizer config that
// embeds CPython and the project's Python sources. Only stdlib + sqlite3 are
// used by PyGo core, so no tricky C-extensions are required at this stage.
func writePyoxidizerSpec(path, projectDir string) error {
	// Collect Python files to embed: the generated module + the framework
	// runtime (core.runtime.pyclient, core.runtime.db).
	spec := fmt.Sprintf(`# Generated by PyGo (pygo build --embed-python). DO NOT EDIT.
# Minimal, single-binary packaging: CPython + app Python embedded.

def make_exe():
    dist = default_python_distribution(python_version="3.11")

    policy = dist.make_python_packaging_policy()
    policy.resources_location = "in-memory"
    policy.resources_location_fallback = "filesystem-relative:lib"

    python_config = dist.make_python_interpreter_config()
    python_config.module_search_paths = ["$ORIGIN/lib"]
    python_config.run_command = "from core.runtime.pyclient import main; main()"

    exe = dist.to_python_executable(
        name="pygo-app",
        packaging_policy=policy,
        config=python_config,
    )

    # Embed the framework runtime (core/) and the project's Python app
    # (app_poc.py / gen_py.py) living in the project directory.
    exe.add_python_resources(exe.read_package_root(
        path=%q,
        packages=["core"],
    ))
    exe.add_python_resources(exe.read_package_root(
        path=%q,
        modules=["app_poc"],
    ))

    return exe

def make_install(exe):
    files = FileManifest()
    files.add_python_resource("bin/", exe)
    return files
`, projectDir, projectDir)

	if err := os.WriteFile(path, []byte(spec), 0o644); err != nil {
		return err
	}
	return nil
}
