// Package generators contains the PyGo code generators.
//
// gen_go.go implements the Go-side generator: from a `.pgo` AST it emits a Go
// source file with model structs, route registrations and handler stubs. The
// stubs delegate business logic to the Python process over the MessagePack
// socket via a runtime helper (runtime.CallPython) that another agent
// implements — here it is only referenced as a clear TODO.
package generators

import (
	"fmt"
	"strings"

	"github.com/ander-labs/pygo/core/transpiler/ast"
)

// GoGenerator is an ast.Visitor that produces Go source.
type GoGenerator struct {
	// PackageName is the package clause of the generated file.
	PackageName string
	buf         strings.Builder
}

// NewGoGenerator creates a generator emitting into the given package.
func NewGoGenerator(pkg string) *GoGenerator {
	if pkg == "" {
		pkg = "generated"
	}
	return &GoGenerator{PackageName: pkg}
}

// Generate walks the program and returns the complete Go source string.
func GenerateGo(prog *ast.Program, pkg string) (string, error) {
	g := NewGoGenerator(pkg)
	if _, err := prog.Accept(g); err != nil {
		return "", err
	}
	return g.buf.String(), nil
}

// goTypeMap maps DSL primitive names to Go types.
var goTypeMap = map[string]string{
	"String":   "string",
	"Int":      "int",
	"Float":    "float64",
	"Bool":     "bool",
	"DateTime": "time.Time",
	"UUID":     "string",
	"Decimal":  "string", // shopspring/decimal later; string for Fase 0
	"Email":    "string",
	"URL":      "string",
	"Phone":    "string",
}

// goType renders a TypeRef into a Go type expression.
func goType(t *ast.TypeRef) string {
	if t == nil {
		return "interface{}"
	}
	switch t.Name {
	case "Optional":
		inner := goType(t.Inner)
		return "*" + strings.TrimPrefix(inner, "*")
	case "Array":
		return "[]" + goType(t.Inner)
	case "Map":
		k := "string"
		if t.Key != nil {
			k = goType(t.Key)
		}
		return "map[" + k + "]" + goType(t.Inner)
	case "ForeignKey":
		return "string" // FK stored as id (Fase 0)
	case "Enum":
		return "string"
	}
	base, ok := goTypeMap[t.Name]
	if !ok {
		base = t.Name // assume a model/struct name
	}
	if t.Optional {
		return "*" + base
	}
	return base
}

func (g *GoGenerator) VisitProgram(n *ast.Program) (interface{}, error) {
	g.buf.WriteString("// Code generated by PyGo transpiler. DO NOT EDIT.\n")
	g.buf.WriteString(fmt.Sprintf("package %s\n\n", g.PackageName))
	g.buf.WriteString("import (\n")
	g.buf.WriteString("\t\"time\"\n\n")
	g.buf.WriteString("\t\"github.com/ander-labs/pygo/core/runtime\"\n")
	g.buf.WriteString(")\n\n")
	g.buf.WriteString("// ensure time is referenced even if no model uses DateTime.\n")
	g.buf.WriteString("var _ = time.Now\n\n")

	// Models -> structs.
	for _, m := range n.Models {
		if _, err := m.Accept(g); err != nil {
			return nil, err
		}
	}

	// Handlers -> stubs.
	for _, h := range n.Handlers {
		if _, err := h.Accept(g); err != nil {
			return nil, err
		}
	}

	// Routes -> registration function.
	g.buf.WriteString("// RegisterRoutes wires the generated routes into a router.\n")
	g.buf.WriteString("// The router type is intentionally an interface stub for Fase 0; the\n")
	g.buf.WriteString("// supervisor/HTTP agent supplies the concrete router.\n")
	g.buf.WriteString("type Router interface {\n")
	g.buf.WriteString("\tHandle(method, path string, h func(args map[string]interface{}) (interface{}, error))\n")
	g.buf.WriteString("}\n\n")
	g.buf.WriteString("func RegisterRoutes(r Router) {\n")
	for _, rt := range n.Routes {
		if _, err := rt.Accept(g); err != nil {
			return nil, err
		}
	}
	g.buf.WriteString("}\n")
	return nil, nil
}

func (g *GoGenerator) VisitModel(n *ast.ModelNode) (interface{}, error) {
	g.buf.WriteString(fmt.Sprintf("// %s is generated from the `model %s` declaration.\n", n.Name, n.Name))
	g.buf.WriteString(fmt.Sprintf("type %s struct {\n", n.Name))
	for _, f := range n.Fields {
		if _, err := f.Accept(g); err != nil {
			return nil, err
		}
	}
	g.buf.WriteString("}\n\n")
	return nil, nil
}

func (g *GoGenerator) VisitField(n *ast.FieldNode) (interface{}, error) {
	goName := exportName(n.Name)
	tag := fmt.Sprintf("`json:\"%s\" msgpack:\"%s\"`", n.Name, n.Name)
	g.buf.WriteString(fmt.Sprintf("\t%s %s %s\n", goName, goType(n.Type), tag))
	return nil, nil
}

func (g *GoGenerator) VisitHandler(n *ast.HandlerNode) (interface{}, error) {
	// Emit a delegate that calls Python over the MessagePack socket and returns
	// the result as interface{} (the router serializes it to JSON/HTML).
	g.buf.WriteString(fmt.Sprintf("// Handler_%s delegates to the Python handler %q over the MessagePack socket.\n", n.Name, n.Name))
	g.buf.WriteString(fmt.Sprintf("func Handler_%s(args map[string]interface{}) (interface{}, error) {\n", n.Name))
	g.buf.WriteString("	return runtime.CallPython(\n")
	g.buf.WriteString(fmt.Sprintf("		%q,\n", n.Name))
	g.buf.WriteString("		args,\n")
	g.buf.WriteString("	)\n")
	g.buf.WriteString("}\n\n")
	return nil, nil
}

func (g *GoGenerator) VisitRoute(n *ast.RouteNode) (interface{}, error) {
	g.buf.WriteString(fmt.Sprintf("\tr.Handle(%q, %q, func(args map[string]interface{}) (interface{}, error) {\n", n.Method, n.Path))
	g.buf.WriteString(fmt.Sprintf("\t\treturn Handler_%s(args)\n", n.Handler))
	g.buf.WriteString("\t})\n")
	return nil, nil
}

func (g *GoGenerator) VisitFunction(n *ast.FunctionNode) (interface{}, error) {
	// Functions are Python-only; Go generates nothing.
	return nil, nil
}

// exportName upper-cases the first letter to produce an exported Go identifier.
func exportName(s string) string {
	if s == "" {
		return s
	}
	// Convert snake_case to CamelCase for idiomatic Go field names.
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}
