// gen_py.go implements the Python-side generator.
//
// From a `.pgo` AST it emits valid Python source (the `gen_py.py` output).
// Because `.pgo` is isomorphic to Python, handler/function bodies are emitted
// almost verbatim (respecting original indentation), models become typed
// classes with a find() method, and handlers register into a HANDLERS dict.
package generators

import (
	"fmt"
	"strings"

	"github.com/ander-labs/pygo/core/transpiler/ast"
)

// PyGenerator is an ast.Visitor that produces Python source.
type PyGenerator struct {
	buf strings.Builder
}

// GeneratePy walks the program and returns the complete Python source string.
func GeneratePy(prog *ast.Program) (string, error) {
	g := &PyGenerator{}
	if _, err := prog.Accept(g); err != nil {
		return "", err
	}
	return g.buf.String(), nil
}

// pyTypeMap maps DSL primitives to Python types.
var pyTypeMap = map[string]string{
	"String":   "str",
	"Int":      "int",
	"Float":    "float",
	"Bool":     "bool",
	"DateTime": "datetime",
	"UUID":     "str",
	"Decimal":  "Decimal",
	"Email":    "str",
	"URL":      "str",
	"Phone":    "str",
}

// pyType renders a TypeRef into a Python type annotation.
func pyType(t *ast.TypeRef) string {
	if t == nil {
		return "object"
	}
	switch t.Name {
	case "Optional":
		return pyType(t.Inner) + " | None"
	case "Array":
		return "list[" + pyType(t.Inner) + "]"
	case "Map":
		k := "str"
		if t.Key != nil {
			k = pyType(t.Key)
		}
		return "dict[" + k + ", " + pyType(t.Inner) + "]"
	case "ForeignKey":
		return "str"
	case "Enum":
		return "str"
	}
	base, ok := pyTypeMap[t.Name]
	if !ok {
		base = t.Name // model class name
	}
	if t.Optional {
		return base + " | None"
	}
	return base
}

func (g *PyGenerator) VisitProgram(n *ast.Program) (interface{}, error) {
	g.buf.WriteString("# Code generated by PyGo transpiler. DO NOT EDIT.\n")
	g.buf.WriteString("from __future__ import annotations\n")
	g.buf.WriteString("from datetime import datetime\n")
	g.buf.WriteString("from decimal import Decimal\n\n")
	g.buf.WriteString("# Handlers register into the shared HANDLERS dict owned by the runtime client,\n")
	g.buf.WriteString("# so the pyclient serve loop can dispatch to them over the socket.\n")
	g.buf.WriteString("from core.runtime.pyclient import HANDLERS\n\n")

	for _, m := range n.Models {
		if _, err := m.Accept(g); err != nil {
			return nil, err
		}
	}
	for _, f := range n.Functions {
		if _, err := f.Accept(g); err != nil {
			return nil, err
		}
	}
	for _, h := range n.Handlers {
		if _, err := h.Accept(g); err != nil {
			return nil, err
		}
	}
	return nil, nil
}

func (g *PyGenerator) VisitModel(n *ast.ModelNode) (interface{}, error) {
	g.buf.WriteString(fmt.Sprintf("class %s:\n", n.Name))
	g.buf.WriteString(fmt.Sprintf("    \"\"\"Generated ORM model from `model %s` (native sqlite3).\"\"\"\n\n", n.Name))

	// Class-level typed attributes.
	for _, f := range n.Fields {
		line := fmt.Sprintf("    %s: %s", f.Name, pyType(f.Type))
		if f.Default != "" {
			line += " = " + f.Default
		}
		g.buf.WriteString(line + "\n")
	}
	g.buf.WriteString("\n")

	// __init__ from keyword args.
	g.buf.WriteString("    def __init__(self, **kwargs):\n")
	for _, f := range n.Fields {
		g.buf.WriteString(fmt.Sprintf("        self.%s = kwargs.get(%q)\n", f.Name, f.Name))
	}
	if len(n.Fields) == 0 {
		g.buf.WriteString("        pass\n")
	}
	g.buf.WriteString("\n")

	// Table + columns DDL (DSL 90%: auto-generated from the model).
	cols := []string{}
	for _, f := range n.Fields {
		cols = append(cols, fmt.Sprintf("%q: %q", f.Name, pySQLType(f.Type)))
	}
	g.buf.WriteString(fmt.Sprintf("    _table = %q\n", toSnake(n.Name)))
	g.buf.WriteString(fmt.Sprintf("    _columns = {%s}\n\n", strings.Join(cols, ", ")))

	// create() classmethod: inserts a row and returns the model instance.
	g.buf.WriteString("    @classmethod\n")
	g.buf.WriteString("    def create(cls, **fields):\n")
	g.buf.WriteString("        \"\"\"Insert a row and return the model instance.\"\"\"\n")
	g.buf.WriteString("        from core.runtime.db import connect, ensure_table\n")
	g.buf.WriteString("        cols = list(fields.keys())\n")
	g.buf.WriteString("        placeholders = \", \".join(\"?\" for _ in cols)\n")
	g.buf.WriteString("        col_names = \", \".join(cols)\n")
	g.buf.WriteString("        conn = connect()\n")
	g.buf.WriteString("        ensure_table(conn, cls._table, [\n")
	g.buf.WriteString("            f\"{name} {typ}\" for name, typ in cls._columns.items()\n")
	g.buf.WriteString("        ])\n")
	g.buf.WriteString("        cur = conn.execute(\n")
	g.buf.WriteString("            f\"INSERT INTO {cls._table} ({col_names}) VALUES ({placeholders})\",\n")
	g.buf.WriteString("            [fields[c] for c in cols],\n")
	g.buf.WriteString("        )\n")
	g.buf.WriteString("        conn.commit()\n")
	g.buf.WriteString("        row = conn.execute(\n")
	g.buf.WriteString("            f\"SELECT * FROM {cls._table} WHERE rowid = ?\", (cur.lastrowid,)\n")
	g.buf.WriteString("        ).fetchone()\n")
	g.buf.WriteString("        conn.close()\n")
	g.buf.WriteString("        return cls.row_to_model(row, cur.lastrowid)\n\n")

	// find() classmethod: by id (rowid for Fase 0).
	g.buf.WriteString("    @classmethod\n")
	g.buf.WriteString("    def find(cls, id):\n")
	g.buf.WriteString("        \"\"\"Look up a row by rowid and return the model instance.\"\"\"\n")
	g.buf.WriteString("        from core.runtime.db import connect\n")
	g.buf.WriteString("        conn = connect()\n")
	g.buf.WriteString("        row = conn.execute(\n")
	g.buf.WriteString("            f\"SELECT * FROM {cls._table} WHERE rowid = ?\", (id,)\n")
	g.buf.WriteString("        ).fetchone()\n")
	g.buf.WriteString("        conn.close()\n")
	g.buf.WriteString("        if row is None:\n")
	g.buf.WriteString("            return None\n")
	g.buf.WriteString("        return cls.row_to_model(row, id)\n\n")

	// row_to_model helper.
	g.buf.WriteString("    @classmethod\n")
	g.buf.WriteString("    def row_to_model(cls, row, rowid=None):\n")
	g.buf.WriteString("        if row is None:\n")
	g.buf.WriteString("            return None\n")
	g.buf.WriteString("        data = {k: row[k] for k in cls._columns.keys()}\n")
	g.buf.WriteString("        if data.get(\"id\") is None and rowid is not None:\n")
	g.buf.WriteString("            data[\"id\"] = rowid\n")
	g.buf.WriteString("        return cls(**data)\n\n")
	return nil, nil
}

func (g *PyGenerator) VisitField(n *ast.FieldNode) (interface{}, error) {
	// Fields are emitted inline by VisitModel; nothing to do standalone.
	return nil, nil
}

func (g *PyGenerator) VisitFunction(n *ast.FunctionNode) (interface{}, error) {
	g.emitDef(n.Name, n.Params, n.ReturnType, n.Body)
	g.buf.WriteString("\n")
	return nil, nil
}

func (g *PyGenerator) VisitHandler(n *ast.HandlerNode) (interface{}, error) {
	g.emitDef(n.Name, n.Params, n.ReturnType, n.Body)
	// Register into HANDLERS.
	g.buf.WriteString(fmt.Sprintf("HANDLERS[%q] = %s\n\n", n.Name, n.Name))
	return nil, nil
}

// VisitWorker emits the worker body as a Python handler and registers it.
// Workers are called by the Go job queue via CallPython (same mechanism as
// regular handlers, just invoked from the queue goroutine instead of the HTTP
// request goroutine).
func (g *PyGenerator) VisitWorker(n *ast.WorkerNode) (interface{}, error) {
	g.emitDef(n.Name, n.Params, nil, n.Body)
	g.buf.WriteString(fmt.Sprintf("HANDLERS[%q] = %s\n\n", n.Name, n.Name))
	return nil, nil
}

func (g *PyGenerator) VisitRoute(n *ast.RouteNode) (interface{}, error) {
	// Routes are Go-only.
	return nil, nil
}

// emitDef writes a `def name(params) -> ret:` header and the verbatim body,
// re-indented by 4 spaces under the def.
func (g *PyGenerator) emitDef(name string, params []*ast.FieldNode, ret *ast.TypeRef, body []string) {
	var ps []string
	for _, p := range params {
		ps = append(ps, fmt.Sprintf("%s: %s", p.Name, pyType(p.Type)))
	}
	sig := fmt.Sprintf("def %s(%s)", name, strings.Join(ps, ", "))
	if ret != nil {
		sig += " -> " + pyType(ret)
	}
	sig += ":"
	g.buf.WriteString(sig + "\n")

	if len(body) == 0 {
		g.buf.WriteString("    pass\n")
		return
	}
	for _, ln := range body {
		if strings.TrimSpace(ln) == "" {
			g.buf.WriteString("\n")
			continue
		}
		g.buf.WriteString("    " + ln + "\n")
	}
}

// pySQLType maps a DSL TypeRef to a SQLite column type. Native/stdlib only.
func pySQLType(t *ast.TypeRef) string {
	if t == nil {
		return "TEXT"
	}
	switch t.Name {
	case "Int":
		return "INTEGER"
	case "Float", "Decimal":
		return "REAL"
	case "Bool":
		return "INTEGER"
	case "String", "UUID", "Email", "URL", "Phone", "DateTime", "Enum", "ForeignKey":
		return "TEXT"
	}
	return "TEXT"
}

// toSnake converts CamelCase model names to snake_case table names.
func toSnake(s string) string {
	if s == "" {
		return s
	}
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteByte(byte(r - 'A' + 'a'))
		} else {
			b.WriteByte(byte(r))
		}
	}
	return b.String()
}
