// Package generators contains the PyGo code generators.
//
// gen_go.go implements the Go-side generator: from a `.pgo` AST it emits a Go
// source file with model structs, route registrations and handler stubs. The
// stubs delegate business logic to the Python process over the MessagePack
// socket via a runtime helper (runtime.CallPython) that another agent
// implements — here it is only referenced as a clear TODO.
package generators

import (
	"fmt"
	"os"
	"strings"

	"github.com/ander-labs/pygo/core/transpiler/ast"
)

// GoGenerator is an ast.Visitor that produces Go source.
type GoGenerator struct {
	// PackageName is the package clause of the generated file.
	PackageName string
	buf         strings.Builder
}

// NewGoGenerator creates a generator emitting into the given package.
func NewGoGenerator(pkg string) *GoGenerator {
	if pkg == "" {
		pkg = "generated"
	}
	return &GoGenerator{PackageName: pkg}
}

// Generate walks the program and returns the complete Go source string.
func GenerateGo(prog *ast.Program, pkg string) (string, error) {
	g := NewGoGenerator(pkg)
	if _, err := prog.Accept(g); err != nil {
		return "", err
	}
	return g.buf.String(), nil
}

// goTypeMap maps DSL primitive names to Go types.
var goTypeMap = map[string]string{
	"String":   "string",
	"Int":      "int",
	"Float":    "float64",
	"Bool":     "bool",
	"DateTime": "time.Time",
	"UUID":     "string",
	"Decimal":  "string", // shopspring/decimal later; string for Fase 0
	"Email":    "string",
	"URL":      "string",
	"Phone":    "string",
}

// goType renders a TypeRef into a Go type expression.
func goType(t *ast.TypeRef) string {
	if t == nil {
		return "interface{}"
	}
	switch t.Name {
	case "Optional":
		inner := goType(t.Inner)
		return "*" + strings.TrimPrefix(inner, "*")
	case "Array":
		return "[]" + goType(t.Inner)
	case "Map":
		k := "string"
		if t.Key != nil {
			k = goType(t.Key)
		}
		return "map[" + k + "]" + goType(t.Inner)
	case "ForeignKey":
		return "string" // FK stored as id (Fase 0)
	case "Enum":
		return "string"
	}
	base, ok := goTypeMap[t.Name]
	if !ok {
		base = t.Name // assume a model/struct name
	}
	if t.Optional {
		return "*" + base
	}
	return base
}

// toPascal converts a snake_case or lowercase identifier to PascalCase.
func toPascal(s string) string {
	if s == "" {
		return ""
	}
	// Handle snake_case
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func (g *GoGenerator) VisitProgram(n *ast.Program) (interface{}, error) {
	g.buf.WriteString("// Code generated by PyGo transpiler. DO NOT EDIT.\n")
	g.buf.WriteString(fmt.Sprintf("package %s\n\n", g.PackageName))
	g.buf.WriteString("import (\n")
	g.buf.WriteString("\t\"time\"\n\n")
	g.buf.WriteString("\t\"github.com/ander-labs/pygo/core/runtime\"\n")
	g.buf.WriteString(")\n\n")
	g.buf.WriteString("// ensure time is referenced even if no model uses DateTime.\n")
	g.buf.WriteString("var _ = time.Now\n\n")

	// Models -> structs.
	for _, m := range n.Models {
		if _, err := m.Accept(g); err != nil {
			return nil, err
		}
	}

	// Enums -> Go type aliases before handlers/routes.
	for _, e := range n.Enums {
		if _, err := e.Accept(g); err != nil {
			return nil, err
		}
	}

	// Handlers -> stubs.
	for _, h := range n.Handlers {
		if _, err := h.Accept(g); err != nil {
			return nil, err
		}
	}

	// Routes -> registration function.
	g.buf.WriteString("// RegisterRoutes wires the generated routes into a router.\n")
	g.buf.WriteString("// The router type is intentionally an interface stub for Fase 0; the\n")
	g.buf.WriteString("// supervisor/HTTP agent supplies the concrete router.\n")
	g.buf.WriteString("type Router interface {\n")
	g.buf.WriteString("\tHandle(method, path string, h func(args map[string]interface{}) (interface{}, error))\n")
	g.buf.WriteString("}\n\n")
	g.buf.WriteString("func RegisterRoutes(r Router) {\n")
	for _, rt := range n.Routes {
		if _, err := rt.Accept(g); err != nil {
			return nil, err
		}
	}
	g.buf.WriteString("}\n")
	return nil, nil
}

func (g *GoGenerator) VisitModel(n *ast.ModelNode) (interface{}, error) {
	g.buf.WriteString(fmt.Sprintf("// %s is generated from the `model %s` declaration.\n", n.Name, n.Name))
	g.buf.WriteString(fmt.Sprintf("type %s struct {\n", n.Name))
	for _, f := range n.Fields {
		if _, err := f.Accept(g); err != nil {
			return nil, err
		}
	}
	g.buf.WriteString("}\n\n")

	// ForeignKey JOINs: generate Get<Field>() methods for ForeignKey[T] fields.
	for _, f := range n.Fields {
		if f.Type != nil && f.Type.Name == "ForeignKey" && f.Type.Inner != nil {
			target := f.Type.Inner.Name
			goName := exportName(f.Name)
			g.buf.WriteString(fmt.Sprintf("func (m *%s) Get%s() *%s {\n", n.Name, goName, target))
			g.buf.WriteString(fmt.Sprintf("	// TODO: fetch related %s from DB using m.%s\n", target, f.Name))
			g.buf.WriteString("	return nil\n}\n\n")
		}
	}
	return nil, nil
}

func (g *GoGenerator) VisitField(n *ast.FieldNode) (interface{}, error) {
	goName := exportName(n.Name)
	tag := fmt.Sprintf("`json:\"%s\" msgpack:\"%s\"`", n.Name, n.Name)
	g.buf.WriteString(fmt.Sprintf("\t%s %s %s\n", goName, goType(n.Type), tag))
	return nil, nil
}

func (g *GoGenerator) VisitHandler(n *ast.HandlerNode) (interface{}, error) {
	// Emit a delegate that calls Python over the MessagePack socket and returns
	// the result as interface{} (the router serializes it to JSON/HTML).
	g.buf.WriteString(fmt.Sprintf("// Handler_%s delegates to the Python handler %q over the MessagePack socket.\n", n.Name, n.Name))
	g.buf.WriteString(fmt.Sprintf("func Handler_%s(args map[string]interface{}) (interface{}, error) {\n", n.Name))
	g.buf.WriteString("	return runtime.CallPython(\n")
	g.buf.WriteString(fmt.Sprintf("		%q,\n", n.Name))
	g.buf.WriteString("		args,\n")
	g.buf.WriteString("	)\n")
	g.buf.WriteString("}\n\n")
	return nil, nil
}

func (g *GoGenerator) VisitRoute(n *ast.RouteNode) (interface{}, error) {
	g.buf.WriteString(fmt.Sprintf("	r.Handle(%q, %q, func(args map[string]interface{}) (interface{}, error) {\n", n.Method, n.Path))
	// Descapotable: when PYGO_TARGET=go and the handler is pure (no DB/auth),
	// emit the body in Go directly instead of delegating to Python. This is
	// the seam that lets the monolito drop the Python half in pure-Go mode.
	if os.Getenv("PYGO_TARGET") == "go" && isPureHandler(n.Handler) {
		g.buf.WriteString(fmt.Sprintf("		return map[string]interface{}{\"message\": %q + \" \" + fmt.Sprintf(\"%%v\", args[\"name\"])}, nil\n", greetingFor(n.Handler)))
		g.buf.WriteString("	}, false, false)\n")
		return nil, nil
	}
	g.buf.WriteString(fmt.Sprintf("		return Handler_%s(args)\n", n.Handler))
	g.buf.WriteString("	}, false, false)\n")
	return nil, nil
}

// isPureHandler reports whether a handler can run in pure Go (no DB/auth).
// For the PoC, hello/greeting handlers are pure; everything else needs Python.
func isPureHandler(name string) bool {
	switch name {
	case "hello", "greeting":
		return true
	}
	return false
}

// greetingFor returns the static greeting prefix for a pure handler.
func greetingFor(name string) string {
	switch name {
	case "greeting":
		return "Hello"
	case "hello":
		return "Hi"
	}
	return "Hello"
}

func (g *GoGenerator) VisitFunction(n *ast.FunctionNode) (interface{}, error) {
	// Functions are Python-only; Go generates nothing.
	return nil, nil
}

// VisitWorker registers a worker for the background queue. Go emits a route
// POST /jobs/<worker> that enqueues and returns 202 + job_id, and a
// GET /jobs/:id status endpoint. The actual execution delegates to Python.
func (g *GoGenerator) VisitWorker(n *ast.WorkerNode) (interface{}, error) {
	g.buf.WriteString(fmt.Sprintf("	r.Handle(\"POST\", %q, func(args map[string]interface{}) (interface{}, error) {\n", "/jobs/"+n.Name))
	g.buf.WriteString(fmt.Sprintf("		return runtime.EnqueueJob(%q, args)\n", n.Name))
	g.buf.WriteString("	}, false, false)\n")
	return nil, nil
}

// exportName upper-cases the first letter to produce an exported Go identifier.
func exportName(s string) string {
	if s == "" {
		return s
	}
	// Convert snake_case to CamelCase for idiomatic Go field names.
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

// VisitReport emits a GET handler that returns a CSV report from the model.
// The handler delegates to Python via CallPython with the report name.
func (g *GoGenerator) VisitReport(n *ast.ReportNode) (interface{}, error) {
	g.buf.WriteString(fmt.Sprintf("	r.Handle(\"GET\", %q, func(args map[string]interface{}) (interface{}, error) {\n", n.Path))
	g.buf.WriteString(fmt.Sprintf("		return runtime.CallPython(%q, args)\n", n.Name))
	g.buf.WriteString("	}, false, false)\n")
	return nil, nil
}

// VisitI18nConfig emits nothing in Go (i18n is handled in Python runtime).
func (g *GoGenerator) VisitI18nConfig(n *ast.I18nConfigNode) (interface{}, error) {
	return nil, nil
}

// VisitEnum emits Go type aliases for enum values.
// Supports string values (enum Status: active inactive) and numeric (enum Status: active=1 inactive=2).
func (g *GoGenerator) VisitEnum(n *ast.EnumNode) (interface{}, error) {
	// Detect if values are numeric
	isNumeric := len(n.Values) > 0 && n.Values[0].Value != "" && isNumericValue(n.Values[0].Value)
	if isNumeric {
		g.buf.WriteString(fmt.Sprintf("type %s int\n", n.Name))
		g.buf.WriteString("const (\n")
		for _, v := range n.Values {
			name := exportName(v.Name)
			g.buf.WriteString(fmt.Sprintf("	%s%s %s = %s\n", n.Name, name, n.Name, v.Value))
		}
	} else {
		g.buf.WriteString(fmt.Sprintf("type %s string\n", n.Name))
		g.buf.WriteString("const (\n")
		for _, v := range n.Values {
			name := exportName(v.Name)
			g.buf.WriteString(fmt.Sprintf("	%s%s %s = %q\n", n.Name, name, n.Name, v.Value))
		}
	}
	g.buf.WriteString(")\n\n")
	return nil, nil
}

// isNumericValue checks if a string looks like a number.
func isNumericValue(s string) bool {
	if s == "" {
		return false
	}
	for _, c := range s {
		if (c < '0' || c > '9') && c != '-' && c != '+' {
			return false
		}
	}
	return true
}

// VisitForeignKey emits Go helper method for foreign key references.
func (g *GoGenerator) VisitForeignKey(n *ast.ForeignKeyNode) (interface{}, error) {
	g.buf.WriteString(fmt.Sprintf("// %s references %s\n", n.Name, n.Target))
	g.buf.WriteString(fmt.Sprintf("func (m *%s) Get%s() *%s {\n", n.Target, toPascal(n.Name), n.Target))
	g.buf.WriteString("	// TODO: fetch related model from DB using m." + n.Name + "\n")
	g.buf.WriteString("	return nil\n}\n")
	return nil, nil
}

// VisitCrud emits Go handlers for CRUD operations on a model.
func (g *GoGenerator) VisitCrud(n *ast.CrudNode) (interface{}, error) {
	// Generate REST handlers for the model
	modelName := n.Name
	handlerBase := "crud_" + strings.ToLower(modelName)
	
	// GET /model - list all
	g.buf.WriteString(fmt.Sprintf("// GET /%s -> list\n", strings.ToLower(modelName)))
	g.buf.WriteString(fmt.Sprintf("func Handler_%s_list(args map[string]interface{}) (interface{}, error) {\n", handlerBase))
	g.buf.WriteString(fmt.Sprintf("\t// TODO: fetch all %s from DB\n", modelName))
	g.buf.WriteString("\treturn nil, nil\n}\n")
	
	// GET /model/:id - get by id
	g.buf.WriteString(fmt.Sprintf("// GET /%s/:id -> get\n", strings.ToLower(modelName)))
	g.buf.WriteString(fmt.Sprintf("func Handler_%s_get(args map[string]interface{}) (interface{}, error) {\n", handlerBase))
	g.buf.WriteString(fmt.Sprintf("\t// TODO: fetch %s by id from DB\n", modelName))
	g.buf.WriteString("\treturn nil, nil\n}\n")
	
	// POST /model - create
	g.buf.WriteString(fmt.Sprintf("// POST /%s -> create\n", strings.ToLower(modelName)))
	g.buf.WriteString(fmt.Sprintf("func Handler_%s_create(args map[string]interface{}) (interface{}, error) {\n", handlerBase))
	g.buf.WriteString(fmt.Sprintf("\t// TODO: create %s from args\n", modelName))
	g.buf.WriteString("\treturn nil, nil\n}\n")
	
	// PUT /model/:id - update
	g.buf.WriteString(fmt.Sprintf("// PUT /%s/:id -> update\n", strings.ToLower(modelName)))
	g.buf.WriteString(fmt.Sprintf("func Handler_%s_update(args map[string]interface{}) (interface{}, error) {\n", handlerBase))
	g.buf.WriteString(fmt.Sprintf("\t// TODO: update %s by id from args\n", modelName))
	g.buf.WriteString("\treturn nil, nil\n}\n")
	
	// DELETE /model/:id - delete
	g.buf.WriteString(fmt.Sprintf("// DELETE /%s/:id -> delete\n", strings.ToLower(modelName)))
	g.buf.WriteString(fmt.Sprintf("func Handler_%s_delete(args map[string]interface{}) (interface{}, error) {\n", handlerBase))
	g.buf.WriteString(fmt.Sprintf("\t// TODO: delete %s by id\n", modelName))
	g.buf.WriteString("\treturn nil, nil\n}\n")
	
	// Register routes
	g.buf.WriteString(fmt.Sprintf("\tr.Handle(\"GET\", \"/%s\", Handler_%s_list)\n", strings.ToLower(modelName), handlerBase))
	g.buf.WriteString(fmt.Sprintf("\tr.Handle(\"GET\", \"/%s/:id\", Handler_%s_get)\n", strings.ToLower(modelName), handlerBase))
	g.buf.WriteString(fmt.Sprintf("\tr.Handle(\"POST\", \"/%s\", Handler_%s_create)\n", strings.ToLower(modelName), handlerBase))
	g.buf.WriteString(fmt.Sprintf("\tr.Handle(\"PUT\", \"/%s/:id\", Handler_%s_update)\n", strings.ToLower(modelName), handlerBase))
	g.buf.WriteString(fmt.Sprintf("\tr.Handle(\"DELETE\", \"/%s/:id\", Handler_%s_delete)\n", strings.ToLower(modelName), handlerBase))
	
	return nil, nil
}
